### ISSUE TITLE
Specify Page Layout

### ISSUE THREAD

**Issue by jefferose** [weDevsOfficial/wedocs-plugin#11]
I'm not using the WeDocs theme so the docs fit my site theme, but by default the theme includes a SIDEBAR on which nothing is showing. You can see this as the large white space to the right in the attached screenshot.
![screen shot 2016-07-04 at 7 01 49 pm](https://cloud.githubusercontent.com/assets/1217201/16572121/d5671ae2-4219-11e6-93e3-6bb2dbb4d64e.png)

I'd like to have the documents on a "Full Width" page specified by the theme. When I use the shortcode, it works on the first page, but as you drill in, the sidebar returns and makes the whole thing very narrow.

Any thoughts? I could add some custom code to detect the page type and override the CSS, but I'd rather not.

**Comment by tareq1988** [comment]
You could use the [templating](https://github.com/tareq1988/wedocs-plugin/wiki/Templating) feature to override the `single-docs.php` by matching your theme perhaps.
