### ISSUE TITLE
Duplicate

### ISSUE THREAD

**Issue by nrkhatana** [weDevsOfficial/wedocs-plugin#12]
Hi There, There should a Section and Article duplication system, so we don't have to retype same articles in another section.

regards,

**Comment by gocandra** [comment]
yes .. this is really important function .. (+1) For this

**Comment by joomapp** [comment]
But this is easily when opening two browser windows and copy / paste the source code of the article in the other ... right ?

**Comment by gocandra** [comment]
More easier when we just click one button to duplicate section & contents inside. Maybe put duplicate icon button between delete & drag icon.

**Comment by Rubaiyat-E-Mohammad** [comment]
May be we can implement this button if feasible. Please have a look @anik-fahmid vai

**Comment by anik-fahmid** [comment]
Copy move feature is on the way.
