### ISSUE TITLE
"Was This Article Helpful To You?" doesn't work or update

### ISSUE THREAD

**Issue by ny404** [weDevsOfficial/wedocs-plugin#140]
Hi there,

Before we begin, we appreciate the time and effort for putting together this Wordpress plugin. It has been a great experience, and it allows us to add our own support documentations for our clients.

One issue we encountered is that when you click either "Yes" or "No" on the "Was This Article Helpful To You?", the counter doesn't update, and it doesn't do anything. All it does is display a refresh icon on the right side of those two options. We tried this on multiple web browsers and disabled any popup and ad blockers, but to no avail. We also checked each documentation page, and it doesn't show the updated "Yes" and "No" counts. Can you please investigate on why this happens?

Best,
Nick, TSPro

<img width="1728" alt="Was This Article Helpful to You issue" src="https://user-images.githubusercontent.com/38796514/187752670-e796119b-453e-4473-816c-4df890948059.png">

https://user-images.githubusercontent.com/38796514/187752762-50e66551-0c1b-4a31-9bca-17cf28b2df7b.mov

<img width="435" alt="Dashboard documentation page counter issue" src="https://user-images.githubusercontent.com/38796514/187753021-85c6bd78-f89d-44c7-963f-46ddba8c9a19.png">

**Comment by anik-fahmid** [comment]
Works fine in the latest version (2.1.8).
