### ISSUE TITLE
Private Docs

### ISSUE THREAD

**Issue by apotenza92** [weDevsOfficial/wedocs-plugin#142]
Hi everyone. Referencing and reopening the issue of #94 

Appears there's currently no way to have private docs visible on the weDocs dashboard?

If so, our options are as follows:

1. Have all docs public, even while they're work in progress. This essentially defeats the purpose of having private docs not visible to the public.
2. Maintain our own independent list of private URLs somewhere else, so we don't unknowingly lose a doc if it's made private.

This isn't ideal. There should be functionality for users to see all Private docs somewhere, either on the dashboard or elsewhere.
Showing private docs on the weDocs Dashboard but with a simple '(Private)' after the title would be perfect.

**Comment by anik-fahmid** [comment]
This issue doesn't exist anymore. Private docs are available in the weDocs dashboard.
