### ISSUE TITLE
[FEATURE] Ctrl+K/Search box on documentation pages

### ISSUE THREAD

**Issue by saiftheboss7** [weDevsOfficial/wedocs-plugin#166]
In a single documentation page, there should be a search box from where we can search all docs. it should be fast and work like live search.

The search should be triggered by Ctrl+K

Demo: https://tailwindcss.com/docs/installation
![CleanShot 2023-11-09 at 14 08 41@2x](https://github.com/weDevsOfficial/wedocs-plugin/assets/19363738/4aa1b564-6f5b-4ff6-812f-17512e9f058e)

**Comment by saiftheboss7** [comment]
@anik-fahmid Work on R&D, Wireframe of this feature as well

**Comment by anik-fahmid** [comment]
This feature has been released (weDocs, version 2.1.0).
