### ISSUE TITLE
Plugin hangs in database update

### ISSUE THREAD

**Issue by AndreasReitberger** [weDevsOfficial/wedocs-plugin#173]
I tried to start the database update, however it now stucks at "Updating"

![image](https://github.com/weDevsOfficial/wedocs-plugin/assets/2952443/9c93b920-e5e0-49fe-9b4c-13623610f689)

Anything I can try or do?

**Comment by anik-fahmid** [comment]
The upgrade may need 1-2 mins tops. If you close the window during the upgrade, it runs in the background. Please let us know if you are facing any issues now. I would recommend contacting our [support](https://wedevs.com/contact/) for further assistance.

**Comment by AndreasReitberger** [comment]
Seems to work now, yes. Was a caching issue, I guess ;) Thank you!
