### ISSUE TITLE
Template override is not working

### ISSUE THREAD

**Issue by tareq1988** [weDevsOfficial/wedocs-plugin#176]
The template override seems to be broken in v2.

Previously I was overriding the sidebar template on the theme. Upgrading to v2 did not override the template. It was loading from the plugin, but should've loaded from the theme.

Reverted the plugin back to v1.7. Need to fix it.

**Comment by Rat01047** [comment]
Fixed in PR: fix/template-overriding-isn't-working-from-site-theme #181
