### ISSUE TITLE
[BUG] Arrow dropdown should be visible on weDocs free version.

### ISSUE THREAD

**Issue by MdAsifHossainNadim** [weDevsOfficial/wedocs-plugin#177]
### [Enhancement] Arrow dropdown should be visible on weDocs free version.

Slack: https://wedevs.slack.com/archives/C02M7JC9013/p1701671423148239

**Comment by anik-fahmid** [comment]
This issue has been fixed (weDocs: Core version 2.1.0; Pro 1.1.0).
