### ISSUE TITLE
Not all docs are shown in  Dashboard

### ISSUE THREAD

**Issue by AndreasReitberger** [weDevsOfficial/wedocs-plugin#200]
I recently saw that not all available docs are shown in the Dashboard anymore.

![image](https://github.com/user-attachments/assets/6ccc3b1f-4e03-4208-b23b-cc647fb7383b)

If I go to the frontend, all docs are visible. I'm also able to edit the invisble docs and categories, however they are not shown in  the dashboard anymore.

![image](https://github.com/user-attachments/assets/1d011cb7-2a93-461e-8340-ccadc9a02da4)

Ref: https://ar3dp.de/dokumentation/

Any help is appreciated :) Thank you!

**Comment by Anower16** [comment]
Hi @AndreasReitberger,

Thanks for reaching out to us. 

Strange! there is no reason from the weDocs end to prohibit any previous docs and hide it from the weDocs section. I believe that you have the latest version of weDocs(both free and Pro) installed. 

Would you please clear your browser cache or check on another browser? If needed, you can try reactivating the plugin as well. 

If the issue exists, please consider sharing your site credentials for deep testing.

Note: Open a support ticket for technical expert help or direct mail to support@wedevs.com
Thanks and have a nice day.

**Comment by AndreasReitberger** [comment]
Hi @Anower16 
thanks for the quick reply. I already have tried this. It is also the same on different devices.
Is there anything else I can do?

**Comment by Anower16** [comment]
Hi @AndreasReitberger,

Thanks for getting back to us.

Without checking, we can not proceed with other resolution steps. Would you please reach out to our technical support? You can directly email "support@wedevs.com" to submit a ticket. We will look into the issue deeply. 

We are excited to hear from you.
Have a nice day.

**Comment by AndreasReitberger** [comment]
Thanks @Anower16 
Email was sent :)

**Comment by anik-fahmid** [comment]
Marked as invalid as this is not a plugin issue.

**Comment by anik-fahmid** [comment]
Closing this. We advised the user to provide FTP creds if needed.
