### ISSUE TITLE
Breadcrumbs working incorrectly

### ISSUE THREAD

**Issue by clonge** [weDevsOfficial/wedocs-plugin#23]
When viewing the main documentation, its name is not in the breadcrumbs. When viewing the child documentation both the parent and child breadcrumb is visible.

I will add a pull request for this issue. I am adding this issue for branch reference.

**Comment by atozsoft** [comment]
hi HenchmenMedia,

did you solve this problem ?

thank you

**Comment by HenchmenMedia** [comment]
I have added a pull request with the fix here:

https://github.com/tareq1988/wedocs-plugin/pull/24/commits/5c906d7a13a8a227cf2d1d96be854864a38e1277

**Comment by atozsoft** [comment]
hi,

thank you so much. fixed.
