### ISSUE TITLE
Sub-levels in the article.

### ISSUE THREAD

**Issue by ghost** [weDevsOfficial/wedocs-plugin#27]
A notable improvement would be to add more sub-levels in an article.
Section
 -Article
 --Article
 ---Article
 ----Article

**Comment by atozsoft** [comment]
i agree. 👍

**Comment by lparkyn** [comment]
I'm using weDocs v1.4.1 and you can do this by using the "classic UI" The link is found at the bottom of the weDocs Docs page. This link shows the WP page management page for the weDocs post type. There you can add/edit a page and change its parent to article. It seems to work for multiple levels.
