### ISSUE TITLE
Feature Request- Edit Doc Suggestion

### ISSUE THREAD

**Issue by maion11** [weDevsOfficial/wedocs-plugin#33]
A form can be included at the bottom of each page stating 'Suggested Edit". It will be engaging to the customers and they will feel valued as you are asking for their opinions or suggestions.

*It should have the minimum number of fields as people don't like to input a lot of details.
![sdf](https://cloud.githubusercontent.com/assets/20102452/21580949/1da60e40-d044-11e6-9669-b8f4aa80510f.PNG)

**Comment by paulovsky** [comment]
@mainul11 you could add a[ form at the bottom of your single.php](https://contactform7.com/faq/can-i-embed-a-contact-form-into-my-template-file/) template that will send out an edit to the author of the post, as well the page where it was sent from. 

I realize that adding a shortcode in the template is not recommendable for performance issues but you might use it as a fix.
