### ISSUE TITLE
Problem page layout

### ISSUE THREAD

**Issue by ghost** [weDevsOfficial/wedocs-plugin#47]
I'm not using the WeDocs theme, but by default the theme includes a **left sidebar**. You can see this as the large white space on the right in the attached screenshot.

![screenshot-2017-10-5 android bitacoradani](https://user-images.githubusercontent.com/9200189/31237171-6c0e7388-a9f6-11e7-9f62-249d92bfa28f.png)

I would like to have the documents on a "Full Width" page specified by the theme. 

I am not a Wordpress developer, I followed the steps given in this [URL]( https://github.com/tareq1988/wedocs-plugin/wiki/Templating), but then I do not know what else I have to do to solve the problem.

**Comment by Rubaiyat-E-Mohammad** [comment]
docs structure has changed a lot.
