### ISSUE TITLE
v1.3.3 Does not show existing Docs

### ISSUE THREAD

**Issue by johnayling** [weDevsOfficial/wedocs-plugin#48]
Update v1.3.3 shows no existing Docs.

Logged in as admin

Wordpress menu WeDocs
Select sub-menu Docs

Existing docs still display on frontend

**Comment by Amanrazdan** [comment]
export the database to external place directly from PHPMyAdmin
deactivate and delete the plugin (don't worry data wont be lost )
now download the plugin from the gitbub repo https://github.com/tareq1988/wedocs
or from original vendor https://wordpress.org/plugins/wedocs/

if still not showing delete the plugin and download the old version from old commit from same GitHub repo

**Comment by Rubaiyat-E-Mohammad** [comment]
not exists anymore
