### ISSUE TITLE
Table of Contents

### ISSUE THREAD

**Issue by ahenning** [weDevsOfficial/wedocs-plugin#6]
The table of contents on the demo http://docs.wedevs.com/docs/dokan/ looks pretty good. Which plugin is used to create this ToC (that understands the weDocs structure).?

**Comment by joomapp** [comment]
Hi, i have the same question as it's not part of the current package i think. Can it be added? Can i donate a bit somehwere to get the same ToC lay-out ?
Besides of that i think you can easily add the Wedocs as a paid extension into your store to support development, i would pay for it. It works nicely.

**Comment by ahenning** [comment]
I'll second both proposals

**Comment by atozsoft** [comment]
hi,

i made some modification to solve this. please try this file.

`<?php
/**
 * The template for displaying a single doc
 *
 * To customize this template, create a folder in your current theme named "wedocs" and copy it there.
 *
 * @package weDocs
 */

$skip_sidebar = ( get_post_meta( $post->ID, 'skip_sidebar', true ) == 'yes' ) ? true : false;

get_header(); ?>

<div id="primary" class="content-area">
    <main id="main" class="site-main" role="main">
        <?php while ( have_posts() ) : the_post(); ?>

            <div class="wedocs-single-wrap">

                <?php if ( ! $skip_sidebar ) { ?>

                    <?php wedocs_get_template_part( 'docs', 'sidebar' ); ?>

                <?php } ?>

                <div class="wedocs-single-content">
                    <?php wedocs_breadcrumbs(); ?>

                    <article id="post-<?php the_ID(); ?>" <?php post_class(); ?> itemscope itemtype="http://schema.org/Article">
                        <header class="entry-header">
                            <?php the_title( '<h1 class="entry-title" itemprop="headline">', '</h1>' ); ?>

                            <?php if ( wedocs_get_option( 'print', 'wedocs_settings', 'on' ) == 'on' ): ?>
                                <a href="#" class="wedocs-print-article wedocs-hide-print wedocs-hide-mobile" title="<?php echo esc_attr( __( 'Print this article', 'wedocs' ) ); ?>"><i class="wedocs-icon wedocs-icon-print"></i></a>
                            <?php endif; ?>
                        </header>
<?php
       $children = wp_list_pages("title_li=&order=menu_order&child_of=". $post->ID ."&echo=0&post_type=" . $post->post_type);         
                   if ( $children ) {
                    
                   echo $children; 
                    
                  }
                ?>

                        <div class="entry-content" itemprop="articleBody">
                            <?php
                                the_content( sprintf(
                                    /* translators: %s: Name of current post. */
                                    wp_kses( __( 'Continue reading %s <span class="meta-nav">&rarr;</span>', 'wedocs' ), array( 'span' => array( 'class' => array() ) ) ),
                                    the_title( '<span class="screen-reader-text">"', '"</span>', false )
                                ) );

                                wp_link_pages( array(
                                    'before' => '<div class="page-links">' . esc_html__( 'Docs:', 'wedocs' ),
                                    'after'  => '</div>',
                                ) );

                                $tags_list = wedocs_get_the_doc_tags( $post->ID, '', ', ' );

                                if ( $tags_list ) {
                                    printf( '<span class="tags-links"><span class="screen-reader-text">%1$s </span>%2$s</span>',
                                        _x( 'Tags', 'Used before tag names.', 'wedocs' ),
                                        $tags_list
                                    );
                                }
                            ?>
                        </div>

                        <footer class="entry-footer wedocs-entry-footer">
                            <?php if ( wedocs_get_option( 'email', 'wedocs_settings', 'on' ) == 'on' ): ?>
                                <span class="wedocs-help-link wedocs-hide-print wedocs-hide-mobile">
                                    <i class="wedocs-icon wedocs-icon-envelope"></i>
                                    <?php printf( '%s <a id="wedocs-stuck-modal" href="%s">%s</a>', __( 'Still stuck?', 'wedocs' ), '#', __( 'How can we help?', 'wedocs' ) ); ?>
                                </span>
                            <?php endif; ?>

                            <div class="wedocs-article-author" itemprop="author" itemscope itemtype="https://schema.org/Person">
                                <meta itemprop="name" content="<?php echo get_the_author(); ?>" />
                                <meta itemprop="url" content="<?php echo get_author_posts_url( get_the_author_meta( 'ID' ) ); ?>" />
                            </div>

                            <meta itemprop="datePublished" content="<?php echo get_the_time( 'c' ); ?>"/>
                            <time itemprop="dateModified" datetime="<?php echo esc_attr( get_the_modified_date( 'c' ) ); ?>"><?php printf( __( 'Updated on %s', 'wedocs' ), get_the_modified_date() ); ?></time>
                        </footer>

                        <?php wedocs_doc_nav(); ?>

                        <?php if ( wedocs_get_option( 'helpful', 'wedocs_settings', 'on' ) == 'on' ): ?>
                            <?php wedocs_get_template_part( 'content', 'feedback' ); ?>
                        <?php endif; ?>

                        <?php if ( wedocs_get_option( 'email', 'wedocs_settings', 'on' ) == 'on' ): ?>
                            <?php wedocs_get_template_part( 'content', 'modal' ); ?>
                        <?php endif; ?>

                    </article>
                </div>
            </div>

        <?php endwhile; ?>

    </main>

</div>

<?php get_footer(); ?>
`

**Comment by atozsoft** [comment]
hi,
i added some codes from wedocs them to wedocs-plugin. :)
please try this for single-docs.php

<?php
/**
 * The template for displaying a single doc
 *
 * To customize this template, create a folder in your current theme named "wedocs" and copy it there.
 *
 * @package weDocs
 */

$skip_sidebar = ( get_post_meta( $post->ID, 'skip_sidebar', true ) == 'yes' ) ? true : false;

get_header(); ?>

<div id="primary" class="content-area">
    <main id="main" class="site-main" role="main">
        <?php while ( have_posts() ) : the_post(); ?>

            <div class="wedocs-single-wrap">

                <?php if ( ! $skip_sidebar ) { ?>

                    <?php wedocs_get_template_part( 'docs', 'sidebar' ); ?>

                <?php } ?>

                <div class="wedocs-single-content">
                    <?php wedocs_breadcrumbs(); ?>

                    <article id="post-<?php the_ID(); ?>" <?php post_class(); ?> itemscope itemtype="http://schema.org/Article">
                        <header class="entry-header">
                            <?php the_title( '<h1 class="entry-title" itemprop="headline">', '</h1>' ); ?>

                            <?php if ( wedocs_get_option( 'print', 'wedocs_settings', 'on' ) == 'on' ): ?>
                                <a href="#" class="wedocs-print-article wedocs-hide-print wedocs-hide-mobile" title="<?php echo esc_attr( __( 'Print this article', 'wedocs' ) ); ?>"><i class="wedocs-icon wedocs-icon-print"></i></a>
                            <?php endif; ?>
                        </header>
<?php
       $children = wp_list_pages("title_li=&order=menu_order&child_of=". $post->ID ."&echo=0&post_type=" . $post->post_type);         
                   if ( $children ) {
                    
                   echo $children; 
                    
                  }
                ?>

                        <div class="entry-content" itemprop="articleBody">
                            <?php
                                the_content( sprintf(
                                    /* translators: %s: Name of current post. */
                                    wp_kses( __( 'Continue reading %s <span class="meta-nav">&rarr;</span>', 'wedocs' ), array( 'span' => array( 'class' => array() ) ) ),
                                    the_title( '<span class="screen-reader-text">"', '"</span>', false )
                                ) );

                                wp_link_pages( array(
                                    'before' => '<div class="page-links">' . esc_html__( 'Docs:', 'wedocs' ),
                                    'after'  => '</div>',
                                ) );

                                $tags_list = wedocs_get_the_doc_tags( $post->ID, '', ', ' );

                                if ( $tags_list ) {
                                    printf( '<span class="tags-links"><span class="screen-reader-text">%1$s </span>%2$s</span>',
                                        _x( 'Tags', 'Used before tag names.', 'wedocs' ),
                                        $tags_list
                                    );
                                }
                            ?>
                        </div>

                        <footer class="entry-footer wedocs-entry-footer">
                            <?php if ( wedocs_get_option( 'email', 'wedocs_settings', 'on' ) == 'on' ): ?>
                                <span class="wedocs-help-link wedocs-hide-print wedocs-hide-mobile">
                                    <i class="wedocs-icon wedocs-icon-envelope"></i>
                                    <?php printf( '%s <a id="wedocs-stuck-modal" href="%s">%s</a>', __( 'Still stuck?', 'wedocs' ), '#', __( 'How can we help?', 'wedocs' ) ); ?>
                                </span>
                            <?php endif; ?>

                            <div class="wedocs-article-author" itemprop="author" itemscope itemtype="https://schema.org/Person">
                                <meta itemprop="name" content="<?php echo get_the_author(); ?>" />
                                <meta itemprop="url" content="<?php echo get_author_posts_url( get_the_author_meta( 'ID' ) ); ?>" />
                            </div>

                            <meta itemprop="datePublished" content="<?php echo get_the_time( 'c' ); ?>"/>
                            <time itemprop="dateModified" datetime="<?php echo esc_attr( get_the_modified_date( 'c' ) ); ?>"><?php printf( __( 'Updated on %s', 'wedocs' ), get_the_modified_date() ); ?></time>
                        </footer>

                        <?php wedocs_doc_nav(); ?>

                        <?php if ( wedocs_get_option( 'helpful', 'wedocs_settings', 'on' ) == 'on' ): ?>
                            <?php wedocs_get_template_part( 'content', 'feedback' ); ?>
                        <?php endif; ?>

                        <?php if ( wedocs_get_option( 'email', 'wedocs_settings', 'on' ) == 'on' ): ?>
                            <?php wedocs_get_template_part( 'content', 'modal' ); ?>
                        <?php endif; ?>

                    </article>
                </div>
            </div>

        <?php endwhile; ?>

    </main>

</div>

<?php get_footer(); ?>

**Comment by atozsoft** [comment]
hi,

i added some codes from wedocs theme to wedocs-plugin to solve this. 

pls try attached theme. dont forget to save it as php file.


[single-docs.txt](https://github.com/tareq1988/wedocs-plugin/files/746675/single-docs.txt)

**Comment by ahenning** [comment]
Thanks, this works when replacing single-docs.php with this update. One thing I have done is to move the children code to after the page content in single-docs. With the children after the content it allows one to have an introduction paragraph before the table of contents.

Thanks!

**Comment by Rubaiyat-E-Mohammad** [comment]
please look into it @anik-fahmid vai

**Comment by Rubaiyat-E-Mohammad** [comment]
TOC already exists
