### ISSUE TITLE
Best way to customize CSS?

### ISSUE THREAD

**Issue by jHetzer** [weDevsOfficial/wedocs-plugin#69]
I would like to customize the plugins css but i don't want to change the plugin files internally for update reasons. When I for example use the plugin "SiteOrigin CSS" it does work but when I load/reload the page i see how the style is changing.
What would be the best/recommented way to accomplish this?

(I already created a child theme to change the slug of the plugin)

**Comment by pwkip** [comment]
You can remove the default styles in 2 steps:
1. You could overwrite the templates (https://github.com/tareq1988/wedocs-plugin/wiki/Templating)
2. Then simply remove the class in the containing div, and replace it with your own class, this will get rid of all the default styles.
