### ISSUE TITLE
Responsive columns

### ISSUE THREAD

**Issue by erikdung** [weDevsOfficial/wedocs-plugin#8]
Hi,
I would like to ask if there is possible to make responsive grid. It looks awful on mobile.

**Comment by tareq1988** [comment]
Can you check the latest version?

**Comment by joomapp** [comment]
Hi, yes better :-) Although i think the breakpoints may be set a little larger and the fill the width with 100%

**Comment by tareq1988** [comment]
You are welcome to submit a pull request :)
