### ISSUE TITLE
write markdown

### ISSUE THREAD

**Issue by PhamVanThinh** [weDevsOfficial/wedocs-plugin#80]
I cann't write markdown in my weDocs.

**Comment by amikoj** [comment]
me too

**Comment by tareq1988** [comment]
You can use [this plugin](https://wordpress.org/plugins/wp-markdown/) to write in markdown.

**Comment by kokers** [comment]
I would recommend [https://wordpress.org/plugins/wp-githuber-md/](https://wordpress.org/plugins/wp-githuber-md/) to write markdown in WP. You can enable it only for wedocs post type.
