### ISSUE TITLE
can not delete an article section completely from the default UI. 

### ISSUE THREAD

**Issue by mdjwel** [weDevsOfficial/wedocs-plugin#99]
When I delete a section (the parent page) of a doc, I assumed that the child pages are deleting with the parent page. But the section is not completely deleting with the child pages.  
I think the article section should be deleted by deleting the parent page from the default UI of the plugin. But currently, we can not delete an article section completely from the default UI.

**Comment by saiftheboss7** [comment]
@mdjwel I think this was fixed for a while. Can you check and let me know?
